const sharp = require('sharp');
const fs = require('fs');

exports.addTextToImage = async (imagePath, outputPath) => {
  try {
    // Load the base image generated by DALL·E
    const baseImage = sharp(imagePath);

    // Add overlay text using SVG (Sharp supports vector text via SVG)
    const svgText = `
      <svg width="1024" height="1024">
        <style>
          .title { fill: black; font-size: 40px; font-family: Arial, sans-serif; }
          .label { fill: black; font-size: 20px; font-family: Arial, sans-serif; }
        </style>
        <text x="50" y="100" class="title">ISO/TC 336 International Standards</text>
        <text x="50" y="200" class="label">1. Essential Equipment: Test tubes, beakers, goggles</text>
        <text x="50" y="250" class="label">2. Safety Measures: Proper waste disposal, protocols</text>
        <text x="50" y="300" class="label">3. Lab Design: Ventilation, safety exits</text>
      </svg>
    `;

    // Composite the text on top of the base image
    await baseImage
      .composite([{ input: Buffer.from(svgText), top: 0, left: 0 }])
      .toFile(outputPath);

    console.log('Text overlay completed');
  } catch (error) {
    console.error('Error adding text to image:', error);
  }
};
